grafana:
  adminPassword: "password"   # lab only (weâ€™ll improve later)
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - grafana.easyitlearning.com
    path: /
    pathType: Prefix

